## Numpy Array operations

In [1]:
import numpy as np

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing", arr[2:7])
print("With Step", arr[1:8:2])
print("Negative indexing", arr[-3])

Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative indexing 8


In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specific element", arr_2d[1, 2])
print("Entire row", arr_2d[1])
print("Entire column", arr_2d[:,2])

Specific element 6
Entire row [4 5 6]
Entire column [3 6 9]


## Sorting


In [ ]:
unsorted = np.array([3, 1, 4, 2, 7, 4, 9, 2, 10])
print("Sorted array", np.sort(unsorted))

# sorting in column wise
arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2D array by column", np.sort(arr_2d_unsorted, axis=0))

# sorting in row wise
arr_2d_unsorted = np.array([[3, 1], [1, 2], [5, 3]])
print("Sorted 2D array by row", np.sort(arr_2d_unsorted, axis=1))

Sorted array [ 1  2  2  3  4  4  7  9 10]
Sorted 2D array by column [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by row [[1 3]
 [1 2]
 [3 5]]


## Filter

In [7]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0]
print("Even numbers", even_number)

Even numbers [ 2  4  6  8 10]


## Filter with mask

In [8]:
mask = numbers > 5
print("Numbers greater than 5 is", numbers[mask])

Numbers greater than 5 is [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [30]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP Where", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP Where [ 6  7  8  9 10]


In [9]:
# Condition_array is defined as:
# if numbers>5:
#     return numbers*2
# else:
#     return numbers

condition_array = np.where(numbers > 5, numbers*2, numbers)
print(condition_array)

condition_array = np.where(numbers > 5, True, False)
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]
[False False False False False  True  True  True  True  True]


### This explains the condition_array and np.where
if (numbers > 5):
    numbers*2
else:
    numbers

### Adding and removing data

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# combine = arr1 + arr2
# print(combine) # This will add the elements of the array and give the output as [5, 7, 9]

combined = np.concatenate([arr1, arr2])
print(combined)

[5 7 9]
[1 2 3 4 5 6]


## array compatibility

In [44]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print("Compatibility shapes", a.shape == b.shape)

Compatibility shapes True


In [48]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row))
print(original)
print("With new row \n", with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("With new column \n", with_new_col)

[[1 2]
 [3 4]]
With new row 
 [[1 2]
 [3 4]
 [5 6]]
With new column 
 [[1 2 7]
 [3 4 8]]


In [52]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, [2])
print("Array after deletion", deleted)
deleted = np.delete(arr, [0, 4, 2])
print("Array after deletion", deleted)

Array after deletion [1 2 4 5]
Array after deletion [2 4]
