## Numpy array and basics
learn numpy array 

In [1]:
import numpy as np

### creating array 


In [ ]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array: ", arr_2d)                                       

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


## list array and numpy array


In [6]:
py_list = [1, 2, 3]
print("Python list multiplication: ", py_list * 2)

np_array = np.array([1, 2, 3]) # Element wise multiplication
print("Python array multiplication: ", np_array *2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)

Python list multiplication:  [1, 2, 3, 1, 2, 3]
Python array multiplication:  [2 4 6]

 List operation time:  0.04621076583862305

 Numpy operation time:  0.0054814815521240234


## Creating array from scratch



In [8]:
zeros = np.zeros((2,3))
print("Zeros array: \n", zeros)

ones = np.ones((2,3))
print("ones array: \n", ones)

full = np.full((2,2), 4)
print("full array: \n", full)

random = np.random.random((2,3))
print("random array: \n", random)

random1 = np.random.randint(2,4, size=(2, 3))
print("random array: \n", random1)

sequence = np.arange(0, 10, 2)
print("Sequence array: \n", sequence)

Zeros array: 
 [[0. 0. 0.]
 [0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[4 4]
 [4 4]]
random array: 
 [[0.15426614 0.94410352 0.65023713]
 [0.09127411 0.35633723 0.58842703]]
random array: 
 [[3 2 3]
 [3 3 2]]
Sequence array: 
 [0 2 4 6 8]


## Vector, Matrix and Tensor

In [15]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Matrix: ", matrix)

tensor = np.array([[[1, 2], [3, 4]], 
                   [[5, 6], [7, 8]]])
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array properties

In [9]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
# arr = np.array([[1, 2, 3], 
#                 [4, 5, 6.6]]) # This will give the output of arr.dtype as float64
print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("DType: ", arr.dtype)


Shape:  (2, 3)
Dimension:  2
Size:  6
DType:  int64


## Array Reshaping


In [20]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3, 4))
print("\n Reshaped array ", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array ", flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array ", raveled)

#Transpose
transpose = reshaped.T
print("\n Transposed array ", transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
